# Generated by Django 6.0.5 on 2026-06-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0052_person_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_in_string',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
