# Generated by Django 6.0.5 on 2026-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0053_alter_location_location_in_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='minimum_order_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
