# Generated by Django 6.0.5 on 2026-06-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0054_restaurant_minimum_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
