# Generated by Django 6.0.5 on 2026-06-11 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0055_deliveryzone_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryzone',
            name='delivery_fee',
        ),
        migrations.CreateModel(
            name='ItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='modelapp.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_addons', to='modelapp.cartitem')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.itemaddon')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='modelapp.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_variant', to='modelapp.cartitem')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelapp.itemvariant')),
            ],
        ),
    ]
