# Generated by Django 6.0.5 on 2026-06-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0056_remove_deliveryzone_delivery_fee_itemaddon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('RIDER_ON_WAY', 'Rider On Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=100),
        ),
    ]
