# Generated by Django 6.0.5 on 2026-06-13 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0058_menuitem_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rider', to='modelapp.rider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PREPARING', 'Preparing'), ('RIDER_ASSIGNED', 'Rider Assigned'), ('RIDER_ON_WAY', 'Rider On Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=100),
        ),
    ]
