# Generated by Django 6.0.5 on 2026-06-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0059_alter_order_rider_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
