# Generated by Django 6.0.5 on 2026-06-14 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0060_order_assigned_at_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_rejected_rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_orders', to='modelapp.rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
