# Generated by Django 6.0.5 on 2026-06-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0061_order_last_rejected_rider_order_rider_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_assignment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
