# Generated by Django 6.0.5 on 2026-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0062_order_rider_assignment_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzone',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
