# Generated by Django 6.0.5 on 2026-06-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0063_deliveryzone_delivery_fee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'restaurant')},
        ),
    ]
