# Generated by Django 6.0.5 on 2026-06-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0064_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='addon_summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='variant_extra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='variant_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
